spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      useServerPrepStmts: true
      cachePrepStmts: true

